name: "Publish Package"

on:
  workflow_dispatch:
    inputs:
      publish_target:
        description: "What is The Point...?..."
        type: choice
        options:
        - gpr
        - npm
        - jsr
        # required: true
      # message:
      #   required: true
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Run tests"
        run: pnpm vitest run

      - name: "Build"
        run: pnpm build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: package-artifact
          path: |
            dist
            package.json
            LICENSE
            README.md
            node_modules
            jsr.json

  publish-gpr:
    if: ${{ inputs.publish_target == 'gpr' || github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: package-artifact

      - name: "Setup Node for GPR"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"

      - name: "Publish to GitHub Packages"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    if: ${{ inputs.publish_target == 'npm' || github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      # id-token: write #: OIDC (not working...)
      contents: read
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: package-artifact

      - name: "Setup Node for npm"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          scope: "@verikami"

      - name: "Publish to npm"
        # run: npm publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-jsr:
    if: ${{ inputs.publish_target == 'jsr' || github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write #: OIDC
      contents: read
    steps:
      # - name: "Checkout"
      #   uses: actions/checkout@v4

      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: package-artifact

      - name: "Publish package"
        run: npx jsr publish
