name: "Publish Package"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Run tests"
        run: pnpm exec vitest run

      - name: "Build"
        run: pnpm build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: package-artifact
          path: |
            dist
            package.json
            LICENSE.md
            README.md
            jsr.json

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: package-artifact

      - name: "Setup Node for npm"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: "Publish to npm"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: package-artifact

      - name: "Setup Node for GPR"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"

      - name: "Publish to GitHub Packages"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-jsr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: package-artifact

      - name: "Setup Node for JSR"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Publish to JSR"
        run: npx jsr publish --yes --token ${{ secrets.JSR_TOKEN }}
